package enums;

public enum EnumLogCategory {
	REGISTER_EMAIL,
	RECOVERY_EMAIL,
	WELCOME_EMAIL,
	INVALID_LOGIN,
	INVALID_EMAIL_RECOVERY,
	USER_BLOCKED_LOGIN,
	TOKEN_INVALID,
	IP_NOT_FOUND,
	OTHER,
	JOB_PENDING_TRANSACTIONS_EMAIL,
	DELETE_ACCOUNT;
}
